In [1]:
import pandas as pd # 파이썬 프로그래밍 언어 > 행,열을 기반으로 되어있는 테이블 형태로 자료 구조를 생성하도록 지원하는 모듈  

FILE_PATH = "연관키워드 20260921 1347.xlsx"

df = pd.read_excel(FILE_PATH, header=1) # 첫번째 행부터 읽어오세요.

df.head() # 상위 5개만 읽어줘

,Unnamed: 0,월간검색수(PC),월간검색수(모바일),월평균클릭수(PC),월평균클릭수(모바일),월평균클릭률(PC),월평균클릭률(모바일),Unnamed: 7,Unnamed: 8
0,도서판매사이트,20,40,0.4,0.3,2.03%,1.03%,중간,5
1,최신베스트셀러,10,30,0.0,0.3,-,0.92%,중간,5
2,국내서점,10,10,0.2,0,1.57%,-,중간,5
3,무료독서,20,50,0.1,1.3,0.49%,2.5%,중간,8
4,베스트소설,50,250,0.0,1.3,-,0.55%,중간,6

In [2]:
df.columns = ["keyword", "search_pc", "search_mobile", "click_pc", "click_mobile", "ctr_pc", "ctr_mobile", "competition", "ad_count"]

df.head()

,keyword,search_pc,search_mobile,click_pc,click_mobile,ctr_pc,ctr_mobile,competition,ad_count
0,도서판매사이트,20,40,0.4,0.3,2.03%,1.03%,중간,5
1,최신베스트셀러,10,30,0.0,0.3,-,0.92%,중간,5
2,국내서점,10,10,0.2,0,1.57%,-,중간,5
3,무료독서,20,50,0.1,1.3,0.49%,2.5%,중간,8
4,베스트소설,50,250,0.0,1.3,-,0.55%,중간,6

In [9]:
 # 파이썬 프로그래밍 언어 > 팬다스 모듈 > 해당 데이터가 어떤 형태와 사이즈의 데이터인지를 우선 확인하는 과정
# 탐색적 데이터 분석 과정 = EDA = Exploratory Data Analysis 
# 데이터 사이즈(행.열), 데이터가 누락된건 없는지, 타입 숫자, 문자 조회!! 데이터의 가치를 판단하기!!

In [3]:
df.shape # 몇 행과 몇 열로 되어 있는지 먼저 확인. 분석할 만한 가치가 있는지 사이즈 크기가 어떤지(사이즈가 클 수록 신뢰도 높음)

(1000, 9)

In [4]:
df.info() # 9개의 열이 각각 어떤 데이터 타입 수집 = 스키마 확인, 각 열마다 결측치 = Null 값 조회의 목적
# object = 문자열 | 혼합데이터 (문자 정수 , 정수 논리)

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   keyword        1000 non-null   str
 1   search_pc      1000 non-null   str
 2   search_mobile  1000 non-null   str
 3   click_pc       1000 non-null   float64
 4   click_mobile   1000 non-null   object
 5   ctr_pc         1000 non-null   str
 6   ctr_mobile     1000 non-null   str
 7   competition    1000 non-null   str
 8   ad_count       1000 non-null   int64
dtypes: float64(1), int64(1), object(1), str(6)
memory usage: 105.3+ KB

In [5]:
df.head(10) # 10개 보여줘 - 기준은 입력된 순서

,keyword,search_pc,search_mobile,click_pc,click_mobile,ctr_pc,ctr_mobile,competition,ad_count
0,도서판매사이트,20,40,0.4,0.3,2.03%,1.03%,중간,5
1,최신베스트셀러,10,30,0.0,0.3,-,0.92%,중간,5
2,국내서점,10,10,0.2,0,1.57%,-,중간,5
3,무료독서,20,50,0.1,1.3,0.49%,2.5%,중간,8
4,베스트소설,50,250,0.0,1.3,-,0.55%,중간,6
5,새로나온책,50,240,1.8,12.5,3.28%,5.32%,중간,8
6,베스트셀러소설,510,"1,500",0.8,35.8,0.16%,2.56%,중간,8
7,예스24몰,10,40,0.0,0,-,-,중간,2
8,오디오북어플,10,120,0.3,1.8,2.07%,1.63%,중간,6
9,2404,100,530,0.9,17.5,0.85%,3.55%,중간,5

In [6]:
df.tail(10) # 아래에서부터 10개 보여줘 - 기준은 입력된 순서

,keyword,search_pc,search_mobile,click_pc,click_mobile,ctr_pc,ctr_mobile,competition,ad_count
990,소위니놀이터,< 10,< 10,0.0,0,-,-,낮음,0
991,도요새잉글리쉬,190,"1,100",0.0,7.8,-,0.76%,낮음,2
992,저자,410,"1,150",0.0,0,-,-,낮음,0
993,로젠택배이사,10,40,0.6,6.2,4%,14.71%,낮음,2
994,밀리종이책,< 10,10,0.0,0,-,-,낮음,0
995,공룡도서,< 10,10,0.0,0.3,-,1.67%,낮음,0
996,울음소리,60,190,0.0,0,-,-,낮음,0
997,자음쓰기연습장,< 10,< 10,0.0,0,-,-,낮음,0
998,한글받침공부장,< 10,< 10,0.0,0,-,-,낮음,0
999,리디은혼,< 10,< 10,0.0,0,-,-,낮음,0

In [15]:
# 현재 데이터안에서 열 제목만 추출 
df.columns

Index(['keyword', 'search_pc', 'search_mobile', 'click_pc', 'click_mobile',
       'ctr_pc', 'ctr_mobile', 'competition', 'ad_count'],
      dtype='str')

In [16]:
# 각 열 = 컬럼 속성값 확인 = 스키마  
df.dtypes

keyword              str
search_pc            str
search_mobile        str
click_pc         float64
click_mobile      object
ctr_pc               str
ctr_mobile           str
competition          str
ad_count           int64
dtype: object

In [17]:
df["keyword"]

0      도서판매사이트
1      최신베스트셀러
2         국내서점
3         무료독서
4        베스트소설
        ...
995       공룡도서
996       울음소리
997    자음쓰기연습장
998    한글받침공부장
999       리디은혼
Name: keyword, Length: 1000, dtype: str

In [19]:
df["keyword"].isna() # False => 결측치가 아니다, True => 결측치!

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: keyword, Length: 1000, dtype: bool

In [20]:
df[df["keyword"].isna()] # False => 결측치가 아니다, True => 결측치!

Empty DataFrame
Columns: [keyword, search_pc, search_mobile, click_pc, click_mobile, ctr_pc, ctr_mobile, competition, ad_count]
Index: []

In [21]:
# 중복된 값이 있다면, 해당 중복된 값의 갯수 // 중복이라면 True

df["keyword"].duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: keyword, Length: 1000, dtype: bool

In [22]:
# 중복된 값이 있다면, 해당 중복된 값의 갯수 // 중복이 많으면 데이터의 신뢰도가 떨어지기 때문에 중복을 먼저 확인
df["keyword"].duplicated().sum()

np.int64(0)

In [25]:
#중복된 값이 있다면, 해당 요소를 찾아와라 

df[df["keyword"].duplicated(keep=False)] # 만약 중복된 값이 있다면 최초 값은 중복된 값이 아니고 두번째 나온 것만 True

Empty DataFrame
Columns: [keyword, search_pc, search_mobile, click_pc, click_mobile, ctr_pc, ctr_mobile, competition, ad_count]
Index: []

In [28]:
#중복된 값이 있다면, 해당 요소를 찾아와라 

df[df["keyword"].duplicated(keep="first")] # 만약 중복된 값이 있다면 최초 값은 중복된 값이 아니고 두번째 나온 것만 True

Empty DataFrame
Columns: [keyword, search_pc, search_mobile, click_pc, click_mobile, ctr_pc, ctr_mobile, competition, ad_count]
Index: []

In [ ]:
# 상관관계 따져보려고 합니다.
# 1857~1936 : 현재 수리 통계학의 아버지 : 칼 피어슨 (영국)
# 상관계수 => 서로 다른 두개의 변수가 얼만큼 상관 관계를 갖고 있는가를 -1 0 1 측정
# 상관계수 => 상관관계가 있다 없다 판단
# 9개의 컬럼으로 구성되어있는 데이터 => 서로 각 열들끼리 상관관계가 있을까?
# 상관관계가 있을 수록 0에서 멀어짐